#! /bin/bash

alias ls="ls -a"
alias .bash="nvim ~/.bashrc.d/ && source ~/.bashrc && echo 'bashrc updated'"

alias .nvim="cd ~/.config/nvim/ && nvim"



# git

alias .gitm="git add . && git commit -m "



