#! /bin/bash

# # Debug (gets *all* your flags)
# cmake -B build/debug -DCMAKE_BUILD_TYPE=Debug
# cmake --build build/debug
#
# # Release (no sanitizers, no -Werror, optimized)
# cmake -B build/release -DCMAKE_BUILD_TYPE=Release
# cmake --build build/release
alias .craftDebug="cmake --build build/debug && echo ------------ BUILD DONE ------------ && .runCraft"
alias .runCraft="./build/debug/CraftpixJam2"
alias .craftRelease="cmake --build build/release && echo ------------ BUILD DONE ------------ && .runCraftRelease"
alias .runCraftRelease="./build/release/CraftpixJam2"

# gives temp permission to write to usb over serial (is that correct?)
# by granting read(4), write (2) (4+2=6) to all users (owner(1st digit), group(2nd digit) and others(3rd digit))
alias .openUsb="read -n 1 -s -r -p "Give full permission to ttyUSB0? press any key to continue, ctrl-c to cancel!" && sudo chmod 666 /dev/ttyUSB0"
